server:
  port: 8888

logging:
  level:
    com.hjxlog: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voir
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml